source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CYFWeekDayPicker_Example', :exclusive => true do
  pod "CYFWeekDayPicker", :path => "../"
end

target 'CYFWeekDayPicker_Tests', :exclusive => true do
  pod "CYFWeekDayPicker", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
